FCHUB WEB APP/web/fchub/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
app_name = 'fchub'
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.fchub_logout, name='logout'),

    path('customers/', views.view_customer, name='customers'),

    path('orders/', views.view_order, name='orders'),
    path('update-status/<int:order_id>/', views.update_status, name='update-status'),
    path('generate-invoice/<int:order_id>/', views.generate_invoice, name='generate-invoice'),
    path('full-details/<int:order_id>/', views.view_full_details, name='full-details'),


    path('category/', views.category_list, name='category'),
    path('category/add', views.add_category, name='add-category'),
    path('category/edit/<int:category_id>/', views.edit_category, name='edit-category'),
    path('category/delete/<int:category_id>/', views.delete_category, name='delete-category'),
    

    path('products/', views.view_product, name='products'),
    path('products/add-products/', views.add_product, name='add-products'),
    path('products/delete-product/<int:pk>', views.delete_product,name='delete-product'),
    path('edit-product/<int:pk>/', views.edit_product, name='edit-product'),
    
    path('materials/', views.view_materials, name='materials'),
    path('materials/edit-regular-material/<int:material_id>/', views.edit_regular_material, name='edit-regular-material'),
    path('materials/delete-regular-material/<int:pk>/', views.delete_regular_material, name='delete-regular-material'),
    
    path('materials/edit-fabric-material/<int:material_id>/', views.edit_fabric_material, name='edit-fabric-material'),
    path('materials/delete-fabric-material/<int:pk>/', views.delete_fabric_material, name='delete-fabric-material'),

    path('materials/choose-material/', views.choose_material_type, name='choose-material'),
    path('materials/add-regular-material/', views.add_regular_material, name='add-regular-material'),
    path('materials/add-fabric-material/', views.add_fabric_material, name='add-fabric-material'),
    
    path('track-purchase/', views.view_purchase, name='track-purchase'), 
    path('track-purchase/add-purchase/', views.add_purchase, name='add-purchase'),
    path('track-purchase/edit-purchase/<int:purchase_id>/', views.edit_purchase, name='edit-purchase'),
    path('track-purchase/delete-purchase/<int:purchase_id>/', views.delete_purchase, name='delete-purchase'),
    
    
    path('manage-business/', views.view_manage_business, name='manage-business'),
    
    path('manage-business/users-admins', views.users_admins, name='users-admins'),
    path('users/', views.users_admins, name='users-admins'),
    path('list-admins/add-admin/', views.add_admin, name='add-admin'),
    path('list-admins/delete-admin/<int:pk>/', views.delete_admin, name='delete-admin'),

    path('upload-csv', views.upload_csv, name='upload-csv'),
    path('delete-csv/', views.delete_csv, name='delete-csv'),
    path('migrate-csv/<int:csv_id>/', views.migrate_csv, name='migrate-csv'),
    path('get-csv-data/<int:file_id>/', views.get_csv_data, name='get-csv-data'),

    path('successful-orders/', views.successful_orders, name='successful-orders'),
    path('download-successful-orders-csv/', views.download_successful_orders_csv, name='download-successful-orders-csv'),

    path('fchub-data-model', views.view_fchub_model, name='fchub-data-model'),
    path('fchub/migrate-fchub-data/', views.migrate_fchub_data, name='migrate-fchub-data'),
    path('fchub/migrate-fchub-data/', views.migrate_fchub_data, name='migrate-fchub-data'),
    path('delete-all-data/', views.delete_all_data, name='delete-all-data'),
    path('delete-fabric-data/', views.delete_fabrics_data, name='delete-fabric-data'),
    path('delete-setType-data/', views.delete_setType_data, name='delete-setType-data'),
    path('delete-color-data/', views.delete_color_data, name='delete-color-data'),
    path('delete-location-data/', views.delete_location_data, name='delete-location-data'),
    path('delete-clean-all-data/', views.delete_clean_all_data, name='delete-clean-all-data'),





    path('fchub/migrate-fabric-data/', views.migrate_fabric_data, name='migrate-fabric-data'),
    path('migrate-category-data/', views.migrate_category_data, name='migrate-category-data'),
    path('migrate-location-data/', views.migrate_location_data, name='migrate-location-data'),
    path('migrate-color-data/', views.migrate_color_data, name='migrate-color-data'),
    path('migrate-training-data/', views.migrate_training_data, name='migrate-training-data'),

    path('sales/', views.sales_for_fabric_list, name='sales-for-fabric-list'),
    path('sales-for-category/', views.SalesForCategoryView.as_view(), name='sales-for-category-list'),
    
    path('sales-for-location/', views.sales_for_location_list, name='sales-for-location'),
    path('sales-for-color/', views.SalesForColorView.as_view(), name='sales-for-color-list'),


   path('train-top-selling/', views.TopSellingModelTrainer.as_view(), name='train-top-selling'),
   path('train-best-selling/', views.BestSellingModelTrainer.as_view(), name='train-best-selling'),
   path('train-winners/', views.WinnersModelTrainer.as_view(), name='train-winners'),
   #path('train-losers/', views.LosersModelTrainer.as_view(), name='train-losers'),

   #path('visualize-products/', views.visualize_products, name='visualize-products'),
   #path('visualize-colors/', views.visualize_products, name='visualize-colors'),
   #path('visualize-orders/', views.visualize_products, name='visualize-orders'),

   path('view-csv-data', views.CsvDataModelTrainer.as_view(), name='csv-data-view'),
   
   path('inventory/', views.inventory_view, name='inventory'),

   path('curtain-ingredients/', views.curtain_ingredients_view, name='curtain-ingredients'), 
   path('curtain-ingredients/add-ingredients', views.add_ingredients, name='add-ingredients'), 
   path('curtain-ingredients/edit-ingredient/<int:ingredient_id>/', views.edit_ingredient, name='edit-ingredient'),
   path('curtain-ingredients/delete-ingredient/<int:ingredient_id>/', views.delete_ingredient, name='delete-ingredient'),
   
   path('send-low-stock-email/<int:item_id>/', views.send_low_stock_email_view, name='send_low_stock_email_view'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FCHUB WEB APP/web/web/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from guest import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index),
    path('guest/',include('guest.urls')),
    path('customer/',include('customer.urls')),
    path('fchub/',include('fchub.urls')),
    path('admin/', admin.site.urls),

    
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FCHUB WEB APP/web/fchub/views.py
from collections import defaultdict
from email.message import EmailMessage
from django.core.mail import send_mail
import calendar
from decimal import Decimal
from io import TextIOWrapper
import io
from itertools import product
import json
from django.db.models import F, Sum
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.cache import cache
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.views import View
import joblib
from matplotlib import pyplot as plt
from sklearn.calibration import LabelEncoder
from sklearn.compose import TransformedTargetRegressor
from sklearn.discriminant_analysis import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from customer.models import Address, Customer, Order, Product, OrderItem
from web.settings import BASE_DIR
from .models import CleanTrainingSets, CsvData, CurtainIngredients, FabricMaterial, Inventory, Material, FleekyAdmin, Category, SalesForCategory, SalesForColor, SalesForFabric, SalesForLocation, SalesForWebData, SuccessfulOrder, Tracker, User, TrainingSets
from .forms import  CategoryForm, CsvUploadForm, CurtainIngredientsForm,FabricMaterialForm, FleekyAdminForm, MaterialForm, ProductForm, TrackerForm
from django.contrib.auth.forms import UserCreationForm
from .models import Csv  # Make sure you have this import
import csv
from .models import CsvData
from django.contrib import messages
import os
from django.db.models import Q
from django.core.exceptions import ValidationError
from datetime import date, datetime
from xhtml2pdf import pisa
from django.template.loader import get_template
import logging
from django.db import transaction
from django.db.models import Subquery, OuterRef
from django.shortcuts import render
from .models import SalesForFabric
import matplotlib.pyplot as plt
from io import BytesIO
import base64
from django.db.models import Count
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from joblib import dump, load
from django.shortcuts import render
from django.http import HttpResponse
import pandas as pd
from sklearn.linear_model import LinearRegression
from django.db.models import Count, Max
from django.http import JsonResponse
from django.middleware.csrf import get_token
from django.views.generic import TemplateView
from django.db.models.functions import TruncMonth
from django.shortcuts import render
from django.db.models import F
from geopy.geocoders import Nominatim
from .models import SalesForLocation
from django.core.serializers.json import DjangoJSONEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import random
import matplotlib.pyplot as plt
from django.views.generic import TemplateView
from django.shortcuts import render
from .models import CleanTrainingSets
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from datetime import datetime
import datetime as dt
from django.utils.crypto import get_random_string
# Create your views here.

@login_required
def dashboard(request):
    # Calculate the counts
    customer_count = Customer.objects.count()
    product_count = Product.objects.count()
    order_count = Order.objects.count()
    pending_order_count = Order.objects.filter(status='Pending').count()
    # Fetch the 5 most recent orders
    orders = Order.objects.all().order_by('-order_date')[:5]
    
    # Prepare lists for ordered products and ordered by
    ordered_products = []
    ordered_bys = []

    for order in orders:
        ordered_items = OrderItem.objects.filter(order=order)
        products = [item.product for item in ordered_items]
        customer = Customer.objects.get(user=order.customer)
        ordered_products.append(products)
        ordered_bys.append(customer)

    context = {
        'customer_count': customer_count,
        'product_count': product_count,
        'order_count': order_count,
        'pending_order_count': pending_order_count,
        'data': zip(ordered_products, ordered_bys, orders),
    }

    return render(request, 'dashboard.html', context)

def fchub_logout(request):
    logout(request)
    cache.clear()  # Clear the cache for all users
    return redirect('guest:index')

@login_required
def view_customer(request):
    customers = Customer.objects.all()   
    return render(request, 'view/customers.html', {'customers': customers})

@login_required
def view_order(request):
    # Get filter parameters from the request
    order_date_filter = request.GET.get('order_date')
    order_status_filter = request.GET.get('order_status')
    total_price_filter = request.GET.get('total_price')
    payment_type_filter = request.GET.get('payment_type')
    order_id_filter = request.GET.get('order_id')  # New filter parameter for Order ID

    # Start with an initial queryset of all orders
    orders = Order.objects.all()
    STATUS_CHOICES = Order.STATUS_CHOICES

    # Apply filters based on user input
    if order_id_filter:  # Check if the filter parameter is not empty
        # Filter orders where the order ID matches the input Order ID
        orders = orders.filter(order_number=order_id_filter)

    if order_date_filter:
        try:
            # Assuming 'order_date' is a DateField in the Order model
            # Convert the input date to a datetime.date object
            order_date_filter = datetime.strptime(order_date_filter, '%Y-%m-%d').date()
            # Filter orders where the order date matches the input date
            orders = orders.filter(order_date=order_date_filter)
        except ValueError:
            # Handle invalid date format gracefully (you can show an error message)
            pass

    if order_status_filter:  # Check if the filter parameter is not empty
        # Filter orders where the status matches the input status
        orders = orders.filter(status=order_status_filter)

    if total_price_filter == "low_to_high":
        # Assuming 'total_price' is a field in the Order model
        orders = orders.order_by('total_price')
    elif total_price_filter == "high_to_low":
        orders = orders.order_by('-total_price')

    if payment_type_filter:
        # Assuming 'payment_method' is a field in the Order model
        if payment_type_filter == 'Online Payment':
            # Correct the filter value to match your model
            orders = orders.filter(payment_method='Online Payment')
        elif payment_type_filter == 'Cash on Delivery (COD)':
            orders = orders.filter(payment_method='Cash on Delivery (COD)')

    # Annotate each order with the sum of total item prices
    orders = orders.annotate(total_item_price=Sum('order_items__item_total'))

    data = []

    for order in orders:
        ordered_items = order.order_items.all()
        ordered_by = Customer.objects.get(user=order.customer)
        data.append((ordered_items, ordered_by, order))

    return render(request, 'view/orders.html', {'data': data, 'status_choices': STATUS_CHOICES})


def calculate_count(setType, qty):
    # Define a dictionary to map set_type to its multiplier
    set_type_multipliers = {
        'Singles': 1,
        '3 in 1': 3,
        '4 in 1': 4,
        '5 in 1': 5,
    }

    # Calculate the count based on set_type and qty
    multiplier = set_type_multipliers.get(setType, 1)  # Default to 1 if set_type is not recognized
    return multiplier * qty


def get_fabric_material_count(fabric_name, color):
    fabric_count = FabricMaterial.objects.filter(
        fabric_name__iexact=fabric_name, color__iexact=color
    ).aggregate(total_count=Sum('fabric_fcount'))['total_count'] or 0
    return fabric_count


def get_material_count(type, name):
    material_count = Material.objects.filter(type=type, name__iexact=name).aggregate(total_count=Sum('count'))['total_count'] or 0
    return material_count
def check_product_availability(order_id):
    order_items = OrderItem.objects.filter(order_id=order_id)

    fabric_names = set()
    fabric_colors = set()

    for item in order_items:
        fabric_names.add(item.product.category.fabric.lower())
        fabric_colors.add(item.product.color.lower())
        if 'thread' in item.product.color.lower():
            color_parts = item.product.color.lower().split(' thread')
            color = color_parts[0].strip()
            fabric_colors.add(color.lower())

    fabric_count_total = 0

    distinct_curtain_fabric_names = CurtainIngredients.objects.values_list('fabric', flat=True).distinct()

    total_possible_qty = float('inf')  # Initialize variable to a high value to find the minimum possible creations

    for fabric_name in distinct_curtain_fabric_names:
        curtain_ingredients_for_name = CurtainIngredients.objects.filter(fabric=fabric_name)

        req_fabric_count = sum(ingredient.fabric_count for ingredient in curtain_ingredients_for_name)
        req_grommet_count = sum(ingredient.grommet_count for ingredient in curtain_ingredients_for_name)
        req_rings_count = sum(ingredient.rings_count for ingredient in curtain_ingredients_for_name)
        req_thread_count = sum(ingredient.thread_count for ingredient in curtain_ingredients_for_name)
        total_length_required = sum(ingredient.length for ingredient in curtain_ingredients_for_name)

        thread_sum = 0
        rings_sum = 0
        grommet_sum = 0

        for color in fabric_colors:

FCHUB WEB APP/web/fchub/templates/navbar/dashboard-manage-business.html
{% load static %}

FCHUB WEB APP/web/fchub/templates/navbar/dashboard-navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Meyawo landing page.">
    <meta name="author" content="Devcrud">
    <title>{% block title %}Admin Panel{% endblock %}</title>
    <!--Tab Icon-->
    <link rel="icon" type="image/x-icon" href="{% static 'imgs/FC_ICON.ico' %}">
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'vendors/themify-icons/css/themify-icons.css' %}">
    <!-- Bootstrap + Steller  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/meyawo.css' %}">
    
    <!-- CSS Bootstrap -->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
    <!-- Page Navbar -->
    <div>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="{%url 'fchub:dashboard'%}">Admin Panel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="productsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Item
                            </a>
                            <div class="dropdown-menu" aria-labelledby="productsDropdown">
                                <a class="dropdown-item" href="{% url 'fchub:inventory'  %}">Manage Inventory</a>
                                <a class="dropdown-item" href="{% url 'fchub:materials'  %}">Manage Materials</a>
                                <a class="dropdown-item" href="{% url 'fchub:curtain-ingredients'  %}">Manage Curtain Ingredients</a>
                            </div>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fchub:dashboard'%}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fchub:customers'%}">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'fchub:orders'  %}">View Orders</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="productsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Products
                            </a>
                            <div class="dropdown-menu" aria-labelledby="productsDropdown">
                                <a class="dropdown-item" href="{% url 'fchub:products'  %}">Manage Products</a>
                                <a class="dropdown-item" href="{% url 'fchub:category'  %}">Manage Category</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dataDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Data
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dataDropdown">
                                <a class="dropdown-item" href="{% url 'fchub:track-purchase' %}">Manage Purchase Data</a>
                                <a class="dropdown-item" href="{% url 'fchub:manage-business'%}">Manage Business</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'fchub:logout' %}" class="ml-4 mt-1 btn btn-light btn-sm">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

FCHUB WEB APP/web/fchub/templates/navbar/dashboard-side-navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Manage Business</title>
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
</head>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <a class="sb-sidenav-menu-heading" href="{% url 'fchub:dashboard'%}">
                         <div><i class="fa-solid fa-chevron-left" ></i> &nbsp;Back</div>
                    </a>
                    <a class="nav-link" href="{% url 'fchub:manage-business'%}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-house"></i></div>
                        Main Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Manage Reports</div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayoutsPopulate" aria-expanded="false" aria-controls="collapseLayoutsPopulate">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-database"></i></div>
                        Populate Data
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayoutsPopulate" aria-labelledby="headingPopulate" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:upload-csv' %}">ADD RAW DATA</a>
                        </nav>
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{%url 'fchub:fchub-data-model' %}">ADD WITHIN FCHUB MODEL</a>
                        </nav>
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:sales-for-fabric-list' %}">View SALES PER PRODUCT</a>
                        </nav>
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:sales-for-category-list'%}">View SALES PER CATEGORY</a>
                        </nav>
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:sales-for-color-list'%}">View SALES PER COLOR</a>
                        </nav>
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:sales-for-location'%}">View SALES PER LOCATION</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayoutsSelling" aria-expanded="false" aria-controls="collapseLayoutsSelling">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        Selling Wise
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayoutsSelling" aria-labelledby="headingSelling" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link"  href="{% url 'fchub:train-top-selling' %}" >
                                TOP SELLING
                            </a>
                            <a class="nav-link" href="{% url 'fchub:train-best-selling'%}" >
                                BEST SELLING
                               
                            </a>
                            <a class="nav-link" href="{% url 'fchub:train-winners'%}" >
                                WINNERS(PER-DATE)
                            </a>
                        </nav>
                    </div>
                    <div class="sb-sidenav-menu-heading">View Data and Reports</div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayoutsView" aria-expanded="false" aria-controls="collapseLayoutsView">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-database"></i></div>
                        View Data
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayoutsView" aria-labelledby="headingView" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{% url 'fchub:csv-data-view'%}">CSV Data</a>
                        </nav>

                    </div>
                    <div class="sb-sidenav-menu-heading">Manage Users</div>
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{% url 'fchub:users-admins' %}"> <i class="fa-regular fa-user"></i> &nbsp; View Users</a>
                        <a class="nav-link" href="{% url 'fchub:add-admin' %}"><i class="fa-solid fa-user-plus"></i> &nbsp; Add Users</a>
                    </nav>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                ({{ request.user }}), {{ active.first_name }} {{ active.last_name }}
            </div>
        </nav>
    </div>